# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rasview_main.ui'
#
# Created: Fri Apr 20 17:55:47 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(640, 480)
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.form_layout = QtGui.QFormLayout(self.layoutWidget)
        self.form_layout.setMargin(0)
        self.form_layout.setObjectName(_fromUtf8("form_layout"))
        self.channel_combo = QtGui.QComboBox(self.layoutWidget)
        self.channel_combo.setObjectName(_fromUtf8("channel_combo"))
        self.form_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.channel_combo)
        self.colormap_label = QtGui.QLabel(self.layoutWidget)
        self.colormap_label.setText(QtGui.QApplication.translate("MainWindow", "Color map", None, QtGui.QApplication.UnicodeUTF8))
        self.colormap_label.setObjectName(_fromUtf8("colormap_label"))
        self.form_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.colormap_label)
        self.colormap_combo = QtGui.QComboBox(self.layoutWidget)
        self.colormap_combo.setObjectName(_fromUtf8("colormap_combo"))
        self.form_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.colormap_combo)
        self.percentile_from_label = QtGui.QLabel(self.layoutWidget)
        self.percentile_from_label.setText(QtGui.QApplication.translate("MainWindow", "Percentile from", None, QtGui.QApplication.UnicodeUTF8))
        self.percentile_from_label.setObjectName(_fromUtf8("percentile_from_label"))
        self.form_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.percentile_from_label)
        self.percentile_from_layout = QtGui.QHBoxLayout()
        self.percentile_from_layout.setObjectName(_fromUtf8("percentile_from_layout"))
        self.percentile_from_slider = QtGui.QSlider(self.layoutWidget)
        self.percentile_from_slider.setOrientation(QtCore.Qt.Horizontal)
        self.percentile_from_slider.setObjectName(_fromUtf8("percentile_from_slider"))
        self.percentile_from_layout.addWidget(self.percentile_from_slider)
        self.percentile_from_spinbox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.percentile_from_spinbox.setObjectName(_fromUtf8("percentile_from_spinbox"))
        self.percentile_from_layout.addWidget(self.percentile_from_spinbox)
        self.form_layout.setLayout(2, QtGui.QFormLayout.FieldRole, self.percentile_from_layout)
        self.percentile_to_label = QtGui.QLabel(self.layoutWidget)
        self.percentile_to_label.setText(QtGui.QApplication.translate("MainWindow", "Percentile to", None, QtGui.QApplication.UnicodeUTF8))
        self.percentile_to_label.setObjectName(_fromUtf8("percentile_to_label"))
        self.form_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.percentile_to_label)
        self.percentile_to_layout = QtGui.QHBoxLayout()
        self.percentile_to_layout.setObjectName(_fromUtf8("percentile_to_layout"))
        self.percentile_to_slider = QtGui.QSlider(self.layoutWidget)
        self.percentile_to_slider.setOrientation(QtCore.Qt.Horizontal)
        self.percentile_to_slider.setObjectName(_fromUtf8("percentile_to_slider"))
        self.percentile_to_layout.addWidget(self.percentile_to_slider)
        self.percentile_to_spinbox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.percentile_to_spinbox.setObjectName(_fromUtf8("percentile_to_spinbox"))
        self.percentile_to_layout.addWidget(self.percentile_to_spinbox)
        self.form_layout.setLayout(3, QtGui.QFormLayout.FieldRole, self.percentile_to_layout)
        self.range_from_label = QtGui.QLabel(self.layoutWidget)
        self.range_from_label.setText(QtGui.QApplication.translate("MainWindow", "Range from", None, QtGui.QApplication.UnicodeUTF8))
        self.range_from_label.setObjectName(_fromUtf8("range_from_label"))
        self.form_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.range_from_label)
        self.range_from_layout = QtGui.QHBoxLayout()
        self.range_from_layout.setObjectName(_fromUtf8("range_from_layout"))
        self.range_from_slider = QtGui.QSlider(self.layoutWidget)
        self.range_from_slider.setOrientation(QtCore.Qt.Horizontal)
        self.range_from_slider.setObjectName(_fromUtf8("range_from_slider"))
        self.range_from_layout.addWidget(self.range_from_slider)
        self.range_from_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.range_from_spinbox.setObjectName(_fromUtf8("range_from_spinbox"))
        self.range_from_layout.addWidget(self.range_from_spinbox)
        self.form_layout.setLayout(4, QtGui.QFormLayout.FieldRole, self.range_from_layout)
        self.range_to_label = QtGui.QLabel(self.layoutWidget)
        self.range_to_label.setText(QtGui.QApplication.translate("MainWindow", "Range to", None, QtGui.QApplication.UnicodeUTF8))
        self.range_to_label.setObjectName(_fromUtf8("range_to_label"))
        self.form_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.range_to_label)
        self.range_to_layout = QtGui.QHBoxLayout()
        self.range_to_layout.setObjectName(_fromUtf8("range_to_layout"))
        self.range_to_slider = QtGui.QSlider(self.layoutWidget)
        self.range_to_slider.setOrientation(QtCore.Qt.Horizontal)
        self.range_to_slider.setObjectName(_fromUtf8("range_to_slider"))
        self.range_to_layout.addWidget(self.range_to_slider)
        self.range_to_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.range_to_spinbox.setObjectName(_fromUtf8("range_to_spinbox"))
        self.range_to_layout.addWidget(self.range_to_spinbox)
        self.form_layout.setLayout(5, QtGui.QFormLayout.FieldRole, self.range_to_layout)
        self.interpolation_label = QtGui.QLabel(self.layoutWidget)
        self.interpolation_label.setText(QtGui.QApplication.translate("MainWindow", "Interpolation", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolation_label.setObjectName(_fromUtf8("interpolation_label"))
        self.form_layout.setWidget(6, QtGui.QFormLayout.LabelRole, self.interpolation_label)
        self.interpolation_combo = QtGui.QComboBox(self.layoutWidget)
        self.interpolation_combo.setObjectName(_fromUtf8("interpolation_combo"))
        self.form_layout.setWidget(6, QtGui.QFormLayout.FieldRole, self.interpolation_combo)
        self.crop_label = QtGui.QLabel(self.layoutWidget)
        self.crop_label.setText(QtGui.QApplication.translate("MainWindow", "Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.crop_label.setObjectName(_fromUtf8("crop_label"))
        self.form_layout.setWidget(7, QtGui.QFormLayout.LabelRole, self.crop_label)
        self.crop_layout = QtGui.QGridLayout()
        self.crop_layout.setObjectName(_fromUtf8("crop_layout"))
        self.crop_top_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_top_spinbox.setObjectName(_fromUtf8("crop_top_spinbox"))
        self.crop_layout.addWidget(self.crop_top_spinbox, 0, 1, 1, 1)
        self.crop_bottom_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_bottom_spinbox.setObjectName(_fromUtf8("crop_bottom_spinbox"))
        self.crop_layout.addWidget(self.crop_bottom_spinbox, 2, 1, 1, 1)
        self.crop_right_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_right_spinbox.setObjectName(_fromUtf8("crop_right_spinbox"))
        self.crop_layout.addWidget(self.crop_right_spinbox, 1, 2, 1, 1)
        self.crop_left_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_left_spinbox.setObjectName(_fromUtf8("crop_left_spinbox"))
        self.crop_layout.addWidget(self.crop_left_spinbox, 1, 0, 1, 1)
        self.form_layout.setLayout(7, QtGui.QFormLayout.FieldRole, self.crop_layout)
        self.zoom_label = QtGui.QLabel(self.layoutWidget)
        self.zoom_label.setText(QtGui.QApplication.translate("MainWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_label.setObjectName(_fromUtf8("zoom_label"))
        self.form_layout.setWidget(8, QtGui.QFormLayout.LabelRole, self.zoom_label)
        self.zoom_slider = QtGui.QSlider(self.layoutWidget)
        self.zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_slider.setObjectName(_fromUtf8("zoom_slider"))
        self.form_layout.setWidget(8, QtGui.QFormLayout.FieldRole, self.zoom_slider)
        self.channel_label = QtGui.QLabel(self.layoutWidget)
        self.channel_label.setText(QtGui.QApplication.translate("MainWindow", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_label.setObjectName(_fromUtf8("channel_label"))
        self.form_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.channel_label)
        self.tabWidget = QtGui.QTabWidget(self.splitter)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menu_bar = QtGui.QMenuBar(MainWindow)
        self.menu_bar.setGeometry(QtCore.QRect(0, 0, 640, 25))
        self.menu_bar.setObjectName(_fromUtf8("menu_bar"))
        self.file_menu = QtGui.QMenu(self.menu_bar)
        self.file_menu.setTitle(QtGui.QApplication.translate("MainWindow", "&File", None, QtGui.QApplication.UnicodeUTF8))
        self.file_menu.setObjectName(_fromUtf8("file_menu"))
        self.help_menu = QtGui.QMenu(self.menu_bar)
        self.help_menu.setTitle(QtGui.QApplication.translate("MainWindow", "&Help", None, QtGui.QApplication.UnicodeUTF8))
        self.help_menu.setObjectName(_fromUtf8("help_menu"))
        MainWindow.setMenuBar(self.menu_bar)
        self.status_bar = QtGui.QStatusBar(MainWindow)
        self.status_bar.setObjectName(_fromUtf8("status_bar"))
        MainWindow.setStatusBar(self.status_bar)
        self.tool_bar = QtGui.QToolBar(MainWindow)
        self.tool_bar.setWindowTitle(QtGui.QApplication.translate("MainWindow", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.tool_bar.setObjectName(_fromUtf8("tool_bar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.open_action = QtGui.QAction(MainWindow)
        self.open_action.setText(QtGui.QApplication.translate("MainWindow", "&Open...", None, QtGui.QApplication.UnicodeUTF8))
        self.open_action.setToolTip(QtGui.QApplication.translate("MainWindow", "Open a data file", None, QtGui.QApplication.UnicodeUTF8))
        self.open_action.setStatusTip(QtGui.QApplication.translate("MainWindow", "Open a data file", None, QtGui.QApplication.UnicodeUTF8))
        self.open_action.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+O", None, QtGui.QApplication.UnicodeUTF8))
        self.open_action.setObjectName(_fromUtf8("open_action"))
        self.close_action = QtGui.QAction(MainWindow)
        self.close_action.setText(QtGui.QApplication.translate("MainWindow", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.close_action.setToolTip(QtGui.QApplication.translate("MainWindow", "Close the currently selected data file", None, QtGui.QApplication.UnicodeUTF8))
        self.close_action.setStatusTip(QtGui.QApplication.translate("MainWindow", "Close the currently selected data file", None, QtGui.QApplication.UnicodeUTF8))
        self.close_action.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+W", None, QtGui.QApplication.UnicodeUTF8))
        self.close_action.setObjectName(_fromUtf8("close_action"))
        self.quit_action = QtGui.QAction(MainWindow)
        self.quit_action.setText(QtGui.QApplication.translate("MainWindow", "&Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_action.setToolTip(QtGui.QApplication.translate("MainWindow", "Quit the application", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_action.setStatusTip(QtGui.QApplication.translate("MainWindow", "Quit the application", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_action.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))
        self.quit_action.setObjectName(_fromUtf8("quit_action"))
        self.about_action = QtGui.QAction(MainWindow)
        self.about_action.setText(QtGui.QApplication.translate("MainWindow", "&About rasViewer", None, QtGui.QApplication.UnicodeUTF8))
        self.about_action.setObjectName(_fromUtf8("about_action"))
        self.about_qt_action = QtGui.QAction(MainWindow)
        self.about_qt_action.setText(QtGui.QApplication.translate("MainWindow", "About QT", None, QtGui.QApplication.UnicodeUTF8))
        self.about_qt_action.setObjectName(_fromUtf8("about_qt_action"))
        self.file_menu.addAction(self.open_action)
        self.file_menu.addAction(self.close_action)
        self.file_menu.addSeparator()
        self.file_menu.addAction(self.quit_action)
        self.help_menu.addAction(self.about_action)
        self.help_menu.addAction(self.about_qt_action)
        self.menu_bar.addAction(self.file_menu.menuAction())
        self.menu_bar.addAction(self.help_menu.menuAction())
        self.tool_bar.addAction(self.open_action)
        self.tool_bar.addAction(self.close_action)
        self.tool_bar.addSeparator()
        self.tool_bar.addAction(self.quit_action)
        self.colormap_label.setBuddy(self.colormap_combo)
        self.percentile_from_label.setBuddy(self.percentile_from_slider)
        self.percentile_to_label.setBuddy(self.percentile_to_slider)
        self.range_from_label.setBuddy(self.range_from_slider)
        self.range_to_label.setBuddy(self.range_to_slider)
        self.interpolation_label.setBuddy(self.interpolation_combo)
        self.crop_label.setBuddy(self.crop_top_spinbox)
        self.zoom_label.setBuddy(self.zoom_slider)
        self.channel_label.setBuddy(self.channel_combo)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(-1)
        QtCore.QObject.connect(self.range_from_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.range_from_spinbox.setValue)
        QtCore.QObject.connect(self.range_to_slider, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.range_to_spinbox.setValue)
        QtCore.QObject.connect(self.range_from_spinbox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.range_from_slider.setValue)
        QtCore.QObject.connect(self.range_to_spinbox, QtCore.SIGNAL(_fromUtf8("valueChanged(int)")), self.range_to_slider.setValue)
        QtCore.QObject.connect(self.quit_action, QtCore.SIGNAL(_fromUtf8("activated()")), MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.channel_combo, self.colormap_combo)
        MainWindow.setTabOrder(self.colormap_combo, self.percentile_from_slider)
        MainWindow.setTabOrder(self.percentile_from_slider, self.percentile_from_spinbox)
        MainWindow.setTabOrder(self.percentile_from_spinbox, self.percentile_to_slider)
        MainWindow.setTabOrder(self.percentile_to_slider, self.percentile_to_spinbox)
        MainWindow.setTabOrder(self.percentile_to_spinbox, self.range_from_slider)
        MainWindow.setTabOrder(self.range_from_slider, self.range_from_spinbox)
        MainWindow.setTabOrder(self.range_from_spinbox, self.range_to_slider)
        MainWindow.setTabOrder(self.range_to_slider, self.range_to_spinbox)
        MainWindow.setTabOrder(self.range_to_spinbox, self.interpolation_combo)
        MainWindow.setTabOrder(self.interpolation_combo, self.crop_top_spinbox)
        MainWindow.setTabOrder(self.crop_top_spinbox, self.crop_left_spinbox)
        MainWindow.setTabOrder(self.crop_left_spinbox, self.crop_right_spinbox)
        MainWindow.setTabOrder(self.crop_right_spinbox, self.crop_bottom_spinbox)
        MainWindow.setTabOrder(self.crop_bottom_spinbox, self.zoom_slider)

    def retranslateUi(self, MainWindow):
        pass

