# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rasview_mdi.ui'
#
# Created: Sat Apr 21 22:33:48 2012
#      by: PyQt4 UI code generator 4.8.5
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MDIWindow(object):
    def setupUi(self, MDIWindow):
        MDIWindow.setObjectName(_fromUtf8("MDIWindow"))
        MDIWindow.resize(658, 525)
        MDIWindow.setWindowTitle(QtGui.QApplication.translate("MDIWindow", "Form", None, QtGui.QApplication.UnicodeUTF8))
        self.verticalLayout_2 = QtGui.QVBoxLayout(MDIWindow)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.splitter = QtGui.QSplitter(MDIWindow)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.form_layout = QtGui.QFormLayout(self.layoutWidget)
        self.form_layout.setMargin(0)
        self.form_layout.setObjectName(_fromUtf8("form_layout"))
        self.channel_combo = QtGui.QComboBox(self.layoutWidget)
        self.channel_combo.setObjectName(_fromUtf8("channel_combo"))
        self.form_layout.setWidget(0, QtGui.QFormLayout.FieldRole, self.channel_combo)
        self.colormap_label = QtGui.QLabel(self.layoutWidget)
        self.colormap_label.setText(QtGui.QApplication.translate("MDIWindow", "Color map", None, QtGui.QApplication.UnicodeUTF8))
        self.colormap_label.setObjectName(_fromUtf8("colormap_label"))
        self.form_layout.setWidget(1, QtGui.QFormLayout.LabelRole, self.colormap_label)
        self.colormap_combo = QtGui.QComboBox(self.layoutWidget)
        self.colormap_combo.setObjectName(_fromUtf8("colormap_combo"))
        self.form_layout.setWidget(1, QtGui.QFormLayout.FieldRole, self.colormap_combo)
        self.percentile_from_label = QtGui.QLabel(self.layoutWidget)
        self.percentile_from_label.setText(QtGui.QApplication.translate("MDIWindow", "Percentile from", None, QtGui.QApplication.UnicodeUTF8))
        self.percentile_from_label.setObjectName(_fromUtf8("percentile_from_label"))
        self.form_layout.setWidget(2, QtGui.QFormLayout.LabelRole, self.percentile_from_label)
        self.percentile_from_layout = QtGui.QHBoxLayout()
        self.percentile_from_layout.setObjectName(_fromUtf8("percentile_from_layout"))
        self.percentile_from_slider = QtGui.QSlider(self.layoutWidget)
        self.percentile_from_slider.setMaximum(10000)
        self.percentile_from_slider.setSingleStep(10)
        self.percentile_from_slider.setPageStep(100)
        self.percentile_from_slider.setOrientation(QtCore.Qt.Horizontal)
        self.percentile_from_slider.setObjectName(_fromUtf8("percentile_from_slider"))
        self.percentile_from_layout.addWidget(self.percentile_from_slider)
        self.percentile_from_spinbox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.percentile_from_spinbox.setMaximum(100.0)
        self.percentile_from_spinbox.setSingleStep(0.1)
        self.percentile_from_spinbox.setObjectName(_fromUtf8("percentile_from_spinbox"))
        self.percentile_from_layout.addWidget(self.percentile_from_spinbox)
        self.form_layout.setLayout(2, QtGui.QFormLayout.FieldRole, self.percentile_from_layout)
        self.percentile_to_label = QtGui.QLabel(self.layoutWidget)
        self.percentile_to_label.setText(QtGui.QApplication.translate("MDIWindow", "Percentile to", None, QtGui.QApplication.UnicodeUTF8))
        self.percentile_to_label.setObjectName(_fromUtf8("percentile_to_label"))
        self.form_layout.setWidget(3, QtGui.QFormLayout.LabelRole, self.percentile_to_label)
        self.percentile_to_layout = QtGui.QHBoxLayout()
        self.percentile_to_layout.setObjectName(_fromUtf8("percentile_to_layout"))
        self.percentile_to_slider = QtGui.QSlider(self.layoutWidget)
        self.percentile_to_slider.setMaximum(10000)
        self.percentile_to_slider.setSingleStep(10)
        self.percentile_to_slider.setPageStep(100)
        self.percentile_to_slider.setProperty("value", 10000)
        self.percentile_to_slider.setOrientation(QtCore.Qt.Horizontal)
        self.percentile_to_slider.setObjectName(_fromUtf8("percentile_to_slider"))
        self.percentile_to_layout.addWidget(self.percentile_to_slider)
        self.percentile_to_spinbox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.percentile_to_spinbox.setMaximum(100.0)
        self.percentile_to_spinbox.setSingleStep(0.1)
        self.percentile_to_spinbox.setProperty("value", 100.0)
        self.percentile_to_spinbox.setObjectName(_fromUtf8("percentile_to_spinbox"))
        self.percentile_to_layout.addWidget(self.percentile_to_spinbox)
        self.form_layout.setLayout(3, QtGui.QFormLayout.FieldRole, self.percentile_to_layout)
        self.range_from_label = QtGui.QLabel(self.layoutWidget)
        self.range_from_label.setText(QtGui.QApplication.translate("MDIWindow", "Range from", None, QtGui.QApplication.UnicodeUTF8))
        self.range_from_label.setObjectName(_fromUtf8("range_from_label"))
        self.form_layout.setWidget(4, QtGui.QFormLayout.LabelRole, self.range_from_label)
        self.range_from_layout = QtGui.QHBoxLayout()
        self.range_from_layout.setObjectName(_fromUtf8("range_from_layout"))
        self.range_from_slider = QtGui.QSlider(self.layoutWidget)
        self.range_from_slider.setMaximum(0)
        self.range_from_slider.setOrientation(QtCore.Qt.Horizontal)
        self.range_from_slider.setObjectName(_fromUtf8("range_from_slider"))
        self.range_from_layout.addWidget(self.range_from_slider)
        self.range_from_spinbox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.range_from_spinbox.setObjectName(_fromUtf8("range_from_spinbox"))
        self.range_from_layout.addWidget(self.range_from_spinbox)
        self.form_layout.setLayout(4, QtGui.QFormLayout.FieldRole, self.range_from_layout)
        self.range_to_label = QtGui.QLabel(self.layoutWidget)
        self.range_to_label.setText(QtGui.QApplication.translate("MDIWindow", "Range to", None, QtGui.QApplication.UnicodeUTF8))
        self.range_to_label.setObjectName(_fromUtf8("range_to_label"))
        self.form_layout.setWidget(5, QtGui.QFormLayout.LabelRole, self.range_to_label)
        self.range_to_layout = QtGui.QHBoxLayout()
        self.range_to_layout.setObjectName(_fromUtf8("range_to_layout"))
        self.range_to_slider = QtGui.QSlider(self.layoutWidget)
        self.range_to_slider.setMaximum(0)
        self.range_to_slider.setOrientation(QtCore.Qt.Horizontal)
        self.range_to_slider.setObjectName(_fromUtf8("range_to_slider"))
        self.range_to_layout.addWidget(self.range_to_slider)
        self.range_to_spinbox = QtGui.QDoubleSpinBox(self.layoutWidget)
        self.range_to_spinbox.setObjectName(_fromUtf8("range_to_spinbox"))
        self.range_to_layout.addWidget(self.range_to_spinbox)
        self.form_layout.setLayout(5, QtGui.QFormLayout.FieldRole, self.range_to_layout)
        self.interpolation_label = QtGui.QLabel(self.layoutWidget)
        self.interpolation_label.setText(QtGui.QApplication.translate("MDIWindow", "Interpolation", None, QtGui.QApplication.UnicodeUTF8))
        self.interpolation_label.setObjectName(_fromUtf8("interpolation_label"))
        self.form_layout.setWidget(6, QtGui.QFormLayout.LabelRole, self.interpolation_label)
        self.interpolation_combo = QtGui.QComboBox(self.layoutWidget)
        self.interpolation_combo.setObjectName(_fromUtf8("interpolation_combo"))
        self.form_layout.setWidget(6, QtGui.QFormLayout.FieldRole, self.interpolation_combo)
        self.crop_label = QtGui.QLabel(self.layoutWidget)
        self.crop_label.setText(QtGui.QApplication.translate("MDIWindow", "Crop", None, QtGui.QApplication.UnicodeUTF8))
        self.crop_label.setObjectName(_fromUtf8("crop_label"))
        self.form_layout.setWidget(7, QtGui.QFormLayout.LabelRole, self.crop_label)
        self.crop_layout = QtGui.QGridLayout()
        self.crop_layout.setObjectName(_fromUtf8("crop_layout"))
        self.crop_top_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_top_spinbox.setMaximum(0)
        self.crop_top_spinbox.setObjectName(_fromUtf8("crop_top_spinbox"))
        self.crop_layout.addWidget(self.crop_top_spinbox, 0, 1, 1, 1)
        self.crop_bottom_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_bottom_spinbox.setMaximum(0)
        self.crop_bottom_spinbox.setObjectName(_fromUtf8("crop_bottom_spinbox"))
        self.crop_layout.addWidget(self.crop_bottom_spinbox, 2, 1, 1, 1)
        self.crop_right_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_right_spinbox.setMaximum(0)
        self.crop_right_spinbox.setObjectName(_fromUtf8("crop_right_spinbox"))
        self.crop_layout.addWidget(self.crop_right_spinbox, 1, 2, 1, 1)
        self.crop_left_spinbox = QtGui.QSpinBox(self.layoutWidget)
        self.crop_left_spinbox.setMaximum(0)
        self.crop_left_spinbox.setObjectName(_fromUtf8("crop_left_spinbox"))
        self.crop_layout.addWidget(self.crop_left_spinbox, 1, 0, 1, 1)
        self.form_layout.setLayout(7, QtGui.QFormLayout.FieldRole, self.crop_layout)
        self.zoom_label = QtGui.QLabel(self.layoutWidget)
        self.zoom_label.setText(QtGui.QApplication.translate("MDIWindow", "Zoom", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_label.setObjectName(_fromUtf8("zoom_label"))
        self.form_layout.setWidget(8, QtGui.QFormLayout.LabelRole, self.zoom_label)
        self.zoom_slider = QtGui.QSlider(self.layoutWidget)
        self.zoom_slider.setOrientation(QtCore.Qt.Horizontal)
        self.zoom_slider.setObjectName(_fromUtf8("zoom_slider"))
        self.form_layout.setWidget(8, QtGui.QFormLayout.FieldRole, self.zoom_slider)
        self.channel_label = QtGui.QLabel(self.layoutWidget)
        self.channel_label.setText(QtGui.QApplication.translate("MDIWindow", "Channel", None, QtGui.QApplication.UnicodeUTF8))
        self.channel_label.setObjectName(_fromUtf8("channel_label"))
        self.form_layout.setWidget(0, QtGui.QFormLayout.LabelRole, self.channel_label)
        self.verticalLayout_2.addWidget(self.splitter)
        self.colormap_label.setBuddy(self.colormap_combo)
        self.percentile_from_label.setBuddy(self.percentile_from_slider)
        self.percentile_to_label.setBuddy(self.percentile_to_slider)
        self.range_from_label.setBuddy(self.range_from_slider)
        self.range_to_label.setBuddy(self.range_to_slider)
        self.interpolation_label.setBuddy(self.interpolation_combo)
        self.crop_label.setBuddy(self.crop_top_spinbox)
        self.zoom_label.setBuddy(self.zoom_slider)
        self.channel_label.setBuddy(self.channel_combo)

        self.retranslateUi(MDIWindow)
        QtCore.QMetaObject.connectSlotsByName(MDIWindow)

    def retranslateUi(self, MDIWindow):
        pass

